version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: go_product_mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: go_product
      MYSQL_USER: go_user
      MYSQL_PASSWORD: go_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: